Community Governance
gatsby-uc/plugins pull request #143
Opened 2022-01-07 18:48 UTC by moonmeister

## Description

Introduce a rough governance doc for initial community management. 

### Documentation

[Rendered Governance Doc](https://github.com/gatsby-uc/plugins/blob/community-mgmt/GOVERNANCE.md)

2022-01-07 18:51 UTC, moonmeister commented
@LekoArts @pragmaticpat Thoughts? Also, I'd like to make one of you, or someone at Gatsby, a Steward as to reduce the bus factor. One of you okay with that or should it be someone like @KyleAMathews?

2022-01-10 08:55 UTC, LekoArts commented
Thanks for putting this up! I'll give it a review tomorrow :)

2022-01-10 15:18 UTC, Burnsy commented
LGTM! 👍🏼

2022-01-11 12:28 UTC, LekoArts requested changes
Thanks for that! Looks already great, left some comments :)

2022-01-11 12:28 UTC, LekoArts commented on CONTRIBUTING.md
> +We have a monthly community meeting that is listed in the Discord](https://discord.gg/gwnqfzetjv) server under events. The meeting is handled there in a voice channel. Anyone is welcome to come, list
```suggestion
We have a monthly community meeting that is listed in the [Discord](https://discord.gg/gwnqfzetjv) server under events. The meeting is handled there in a voice channel. Anyone is welcome to come, listen, and join the conversation. The meeting is usually held on the last Tuesday of the month.
```

2022-01-11 12:28 UTC, LekoArts commented on CONTRIBUTING.md
> +Not all packages NEED to be run through Babel. Any project with a non-insignificant amount of code should most likely be transpiled for compatability reasons. `babel-preset-gatsby-package` makes this
```suggestion
Not all packages **need** to be run through Babel. Any project with a non-insignificant amount of code should most likely be transpiled for compatability reasons. `babel-preset-gatsby-package` makes this easy but this does add a slight bit of maintenance overhead. Here is the minimal config for transpiling that a package will need.
```

Capslock is not great on screenreaders 👂

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +> Note: OUr model is extremely new, and not yet binding. Once merged into the `main` branch, we will trial what's outlined here and make changes based on any feedback. All changes will go through the
```suggestion
> Note: Our model is extremely new, and not yet binding. Once merged into the `main` branch, we will trial what's outlined here and make changes based on any feedback. All changes will go through the PR review process. This note will be removed when this governance model is seen as binding.
```

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +At this time we have no specifics for this role. as the community grows we anticipate privleges to come. If you have ideas here please let us know!
```suggestion
At this time we have no specifics for this role. As the community grows we anticipate privileges to come. If you have ideas here please let us know!
```

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +### Level 2 (L2) - Maintainer
Should Level 1 be (L1) then, too? (In the heading)

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +The **Maintainer** role is available to any contributor who wants to join the team and take part in the long-term maintenance of a plugin(s) in the GUC.
```suggestion
The **Maintainer** role is available to any contributor who wants to join the team and take part in the long-term maintenance of plugins in the GUC.
```

From my standpoint it's also clear this way that it doesn't necessarily mean you maintain all plugins

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +- Invitation to the private #maintainers channel on Discord.
```suggestion
- Invitation to the private `#maintainers` channel on Discord.
```

@pragmaticpat we want us (Gatsby) commit ourselves to also be in that channel and help out as needed. As in that sentence would also say: "[...] where also the Gatsby team can be reached"

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +- Ability to merge _some_ GitHub PRs.
What's "some"?

2022-01-11 12:28 UTC, LekoArts commented on GOVERNANCE.md
> +- Define project direction and planning
I'd say that L2 members can weigh in on that, too?

2022-01-11 13:11 UTC, pragmaticpat commented
Thanks @moonmeister ! - I'll look at this one later on today / this evening. 👍

2022-01-11 15:46 UTC, moonmeister commented on GOVERNANCE.md
> +- Ability to merge _some_ GitHub PRs.
This is leftover from astro. I thought I'd leave it. ATM they could merge anything.

2022-01-12 00:42 UTC, pragmaticpat reviewed
Thanks for assembling this. I really like the fact that you're deriving the initial governance from Astro's model. I'm also a fan of Astro's model :)

2022-01-12 00:42 UTC, pragmaticpat commented on GOVERNANCE.md
> +The Maintainer role is critical to the long-term health of GUC plugins. Maintainers act as the first line of defense when it comes to new issues, pull requests and Discord activity. Maintainers are m
```suggestion
The Maintainer role is critical to the long-term health of GUC plugins. Maintainers act as the first line of support when it comes to new issues, pull requests and Discord activity. Maintainers are most likely the first people that a user will interact with on Discord or GitHub.
```

2022-01-12 00:42 UTC, pragmaticpat commented on GOVERNANCE.md
> +- Participate in the project as a team player.
```suggestion
- Participate in the project as a team player
```

2022-01-12 00:42 UTC, pragmaticpat commented on GOVERNANCE.md
> +- Participate in the project as a team player.
The intention here is just for consistency - either a trailing `.` or no trailing `.` on list items

2022-01-12 00:42 UTC, pragmaticpat commented on GOVERNANCE.md
> +- Ability to decide on moderation decisions
```suggestion
- Final say on moderation decisions
```

2022-01-12 00:46 UTC, pragmaticpat commented on GOVERNANCE.md
> +- Invitation to the private #maintainers channel on Discord.
@LekoArts - I don't see which sentence you're specifically referencing. That said, I agree that there can be a mention of a Gatsby team member that at least checks in on some frequency. We should probably consider some sense of "office hours" for supporting any questions that arise. 

How's that sound to you and @moonmeister ?

2022-01-12 16:41 UTC, moonmeister commented on GOVERNANCE.md
> +- Invitation to the private #maintainers channel on Discord.
Doesn't sound like that needs to be in the governance docs. If we want to mention this as a resource in the contributing docs that seems fine. Unless we want to give maintainers explicit access to the Gatsby team.

2022-01-12 16:44 UTC, moonmeister commented on GOVERNANCE.md
> +The Maintainer role is critical to the long-term health of GUC plugins. Maintainers act as the first line of defense when it comes to new issues, pull requests and Discord activity. Maintainers are m
I can understand not using the word defense. But given the Readme where we explicitly say we're not providing support this seems like a contradiction. Thoughts?

2022-01-13 07:35 UTC, LekoArts commented on GOVERNANCE.md
> +- Invitation to the private #maintainers channel on Discord.
> If we want to mention this as a resource in the contributing docs that seems fine.

👍

2022-01-13 07:35 UTC, LekoArts approved these changes

2022-01-16 01:05 UTC, merged